-- Create the table to store market analysis reports
CREATE TABLE IF NOT EXISTS public.market_analysis_reports (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    title text NOT NULL,
    report_data jsonb NOT NULL,
    CONSTRAINT market_analysis_reports_pkey PRIMARY KEY (id),
    CONSTRAINT market_analysis_reports_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE
);

-- Add comments to the table and columns for clarity
COMMENT ON TABLE public.market_analysis_reports IS 'Stores saved market analysis reports generated by the AI.';
COMMENT ON COLUMN public.market_analysis_reports.report_data IS 'The full JSONB data of the generated report, including SWOT analysis, trends, and suggestions.';

-- Enable Row Level Security (RLS) on the new table
ALTER TABLE public.market_analysis_reports ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if they exist, to ensure this script is re-runnable
DROP POLICY IF EXISTS "Allow individual read access on market_analysis_reports" ON public.market_analysis_reports;
DROP POLICY IF EXISTS "Allow individual insert access on market_analysis_reports" ON public.market_analysis_reports;
DROP POLICY IF EXISTS "Allow individual delete access on market_analysis_reports" ON public.market_analysis_reports;

-- Create RLS policies
-- 1. Allow users to read their own reports.
CREATE POLICY "Allow individual read access on market_analysis_reports"
ON public.market_analysis_reports
FOR SELECT
USING (auth.uid() = user_id);

-- 2. Allow users to create reports for themselves.
CREATE POLICY "Allow individual insert access on market_analysis_reports"
ON public.market_analysis_reports
FOR INSERT
WITH CHECK (auth.uid() = user_id);

-- 3. Allow users to delete their own reports.
CREATE POLICY "Allow individual delete access on market_analysis_reports"
ON public.market_analysis_reports
FOR DELETE
USING (auth.uid() = user_id);
