-- Create the table for value strategies
CREATE TABLE
  public.value_strategies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    virality_axis TEXT NULL,
    content_method TEXT NULL,
    value_purpose TEXT NULL,
    practical_example TEXT NULL,
    CONSTRAINT value_strategies_pkey PRIMARY KEY (id)
  );

-- Enable Row Level Security on the new table
ALTER TABLE public.value_strategies ENABLE ROW LEVEL SECURITY;

-- Create a policy to allow authenticated users to read all rows
CREATE POLICY "Allow authenticated read access"
ON public.value_strategies
FOR SELECT
TO authenticated
USING (true);

-- Seed the table with the initial 50 strategies in English
INSERT INTO public.value_strategies (virality_axis, content_method, value_purpose, practical_example)
VALUES
  ('EMOTION (Humor)', 'Meme with Contextual Commentary', 'Immediate identification with a common niche pain point.', 'Meme of a dog with coffee, with text: "Me at 3 a.m., waiting for the algorithm to give me organic reach."'),
  ('EMOTION (Surprise)', '7-Second Plot Twist', 'Break expectations with an unexpected turn that encourages re-watching.', 'Show a complex cooking process and end up using a fast-food product.'),
  ('EMOTION (Authenticity)', 'Sincere "Behind-the-Scenes" Video', 'Humanize the brand by showing mistakes or the real, fun side of work.', 'The CEO failing or bloopering while trying to record a serious tutorial.'),
  ('EMOTION (Curiosity/Outrage)', 'Relevant Social Experiment', 'Generate debate and reflection on a social or consumer issue.', 'Interviewing people on the street about a basic financial myth.'),
  ('EMOTION (Inspiration)', 'Overcoming Storytelling (Carousel)', 'Connect emotionally by narrating failure and subsequent success.', '"How a $10,000 mistake taught me this key lesson for my business."'),
  ('EMOTION (Controversy)', 'Radical Critique of a Trend', 'Challenge an established "rule" in the industry to generate debate.', 'Video: "Why ''Work Hard'' is the worst productivity advice that exists?"'),
  ('EMOTION (Identification)', 'Quick Interview with "Common People"', 'Show that user experiences are universal and fun.', '"What is your worst online shopping experience during Black Friday?"'),
  ('EMOTION (Hope)', '"Act of Kindness" Campaign', 'Inspire the audience by showing the brand genuinely helping.', 'Paying the bill for a customer who is starting their own business.'),
  ('EMOTION (Humor)', 'Use of Viral Audio Out of Context', 'Adapt a popular song or sound to an uncomfortable everyday work situation.', 'Reel using viral audio about a common frustration with a client''s email.'),
  ('EMOTION (Fun)', 'Challenge with Reward', 'Invite massive action by asking to imitate a simple and useful challenge.', '"The #OrganizationChallenge: 3 steps to clean your desk in 60 seconds."'),
  ('UTILITY (Immediacy)', 'Stop-Motion Mini-Tutorial', 'Teach a complete process in a minimal amount of time, ideal for saving.', 'Voiceless video showing the assembly of furniture or the solution to a software bug in 15 seconds.'),
  ('UTILITY (Resource)', 'Definitive Guide in PDF (No Lead)', 'Offer a high-value resource without barriers (no email required) to maximize sharing.', 'A "100 Points to Check Before Launching Your Website" checklist.'),
  ('UTILITY (Time-Saving)', 'Cheat Sheet', 'Provide an image or carousel with essential shortcuts or commands.', 'Infographic with all the keyboard shortcuts for Photoshop or Excel.'),
  ('UTILITY (Clarity)', 'Complex Process Infographic', 'Simplify a difficult workflow into a digestible image.', 'A flowchart explaining the 10 stages of real estate investment.'),
  ('UTILITY (Basic Education)', 'Niche Dictionary for Beginners', 'Clarify technical terms that confuse the new audience.', 'Carousel explaining 5 digital marketing terms people often misuse.'),
  ('UTILITY (Decision)', '"This vs. That" Post (Comparison)', 'Help the user make a purchase decision with an impartial analysis.', 'Article or reel comparing iPhone vs. Android for photographers.'),
  ('UTILITY (Tool)', 'Free Editable Template', 'Offer a ready-to-use tool that saves hours of work.', 'An editable Google Sheets file for creating a monthly budget.'),
  ('UTILITY (Critical Knowledge)', 'Debunking a Popular Product Flaw', 'Provide information that the manufacturer doesn''t, building trust.', 'Video analyzing why a feature of a famous mobile phone fails and how to disable it.'),
  ('UTILITY (Evidence)', 'Case Study Based on Open Metrics', 'Share the real numbers (traffic, ROI, engagement) of a project.', 'Post with a screenshot from Google Analytics of a content success.'),
  ('UTILITY (Advice)', '"Ask Me Anything" (AMA) Live', 'Offer free and personalized advice through a Q&A session.', 'A 30-minute live session answering technical questions about programming.'),
  ('TIMING (Perspective)', 'Quick Commentary on a News Story (Op-Ed)', 'Relate a current event to the principles of your niche.', 'Text post giving your professional opinion on the latest interest rate change.'),
  ('TIMING (Humor)', 'Parody of a Famous Commercial', 'Leverage the popularity of a current advertising campaign.', 'Recreate a viral Coca-Cola ad, but replace the drink with your product.'),
  ('TIMING (Adaptation)', 'Use of Trending Music with an Educational Gesture', 'Use the trending audio on a Reel to show data and important tips.', 'Reel with a simple dance pointing to 5 industry facts on screen.'),
  ('TIMING (Summary)', 'The "Top 5" of the Week/Month', 'Save your audience time by recapping the most important news.', 'Carousel with "The 5 most relevant tech news of the week".'),
  ('TIMING (Game)', 'Bracket or Viral Voting Poll', 'Create an interactive and fun competition based on current events.', 'Pitting the 8 best marketing books of the year against each other in a voting tournament.'),
  ('TIMING (Sincerity)', 'Real-Time Reaction Video', 'Show a spontaneous and unfiltered opinion on a launch or event.', 'Record your immediate reaction to the announcement of a new iPhone or console.'),
  ('TIMING (Vision)', 'Predictive Analysis (Forecasting)', 'Share bold predictions about the future of the industry.', 'Post with 3 controversial predictions about the future of remote work in 2026.'),
  ('TIMING (Education)', '"Behind the Trend" (Trend Analysis)', 'Explain the psychology or reasons behind a viral trend.', 'Video that breaks down why a TikTok challenge became so popular.'),
  ('TIMING (Nostalgia)', 'Annual Recap / End of Year', 'Look back to celebrate successes and the value delivered.', 'Carousel of "The 10 most useful hacks we shared this year".'),
  ('TIMING (Solution)', 'Direct Answer to a Trending Question', 'Use a popular hashtag to solve a specific doubt.', '30-second video using a trend to answer a current tax question.'),
  ('COMMUNITY (Recognition)', 'User-Generated Content (UGC)', 'Validate and recognize the creativity of customers and followers.', 'Publish a repost from a customer using your product in an innovative way.'),
  ('COMMUNITY (Challenge)', 'Knowledge Trivia or Quiz', 'Encourage participation and test the audience''s knowledge.', 'Multiple-choice questions in Stories about fun facts from your niche.'),
  ('COMMUNITY (Reach)', 'Collaboration with a Micro-Influencer', 'Unite audiences and validate the message with a credible voice in a niche.', 'A joint Live session with a small expert in little-known but useful software.'),
  ('COMMUNITY (Co-Creation)', 'Decision Poll or Survey', 'Make the audience feel ownership of the content by deciding the next piece.', 'Ask in Stories if they prefer a post on "Finance" or "Productivity" next week.'),
  ('COMMUNITY (Interaction)', 'Mass Comment Challenge', 'Incentivize mass response with a promise of exclusive content.', '"Comment the word KEYWORD to unlock a free template in my DM."'),
  ('COMMMUNITY (Attention)', 'Video Response to a Comment', 'Personalize the interaction by answering a common question with a video.', 'Record a Reel answering an interesting question left in the previous post.'),
  ('COMMUNITY (Transparency)', '"Controversial FAQs" Content', 'Demonstrate openness by addressing difficult topics or brand criticisms.', 'Video answering the 5 most uncomfortable questions asked about your service.'),
  ('COMMUNITY (Inclusion)', 'Create a Collaborative Glossary', 'Ask the audience for definitions or ideas for a future resource.', 'Post asking people to define success in one word in the comments.'),
  ('COMMUNITY (Feedback)', 'Portfolio or Work Review', 'Offer value in exchange for visibility, giving constructive criticism.', 'Live session reviewing and giving feedback on followers'' graphic designs.'),
  ('COMMUNITY (Fun)', 'Create a Brand GIF or Sticker', 'Create an easy-to-share element in chats that represents a brand emotion.', 'An animated GIF of an employee making a gesture of joy for an achievement.'),
  ('DEPTH (Audio Summary)', 'Podcast Clip with Dynamic Subtitles', 'Turn long content into a high-value, easy-to-digest "sample".', 'A 60-second clip of the most impactful phrase from a 1-hour interview.'),
  ('DEPTH (Narrative)', '"Threads" of X (Twitter)', 'Tell a story or summarize a long article in a chain of posts.', 'Summarize a 3,000-word research paper in 12 narrative and engaging tweets.'),
  ('DEPTH (Motivation)', 'Inspirational Quotes with Data Graphics', 'Provide a burst of inspiration based on hard evidence.', 'A motivational quote from your Ebook, accompanied by the metric that validates it.'),
  ('DEPTH (Micro-Education)', '"Mini-Class" Reel from Webinar', 'Distill the most valuable points from a long event into a very short video.', 'Cut 3 key tips from a 60-minute webinar into a 45-second Reel.'),
  ('DEPTH (Expectation)', 'The "Teaser" of the Next Project', 'Generate excitement and anticipation for something big that''s coming.', 'Short video showing the behind-the-scenes of your next book cover.'),
  ('DEPTH (Reference)', '"Printable" Golden Rules Poster', 'Create a resource that the audience will want to save, print, or use as a wallpaper.', 'A minimalist design with the "5 Fundamental Rules of Good Saving".'),
  ('DEPTH (Structure)', 'Unique Mind Map or Diagram', 'Organize complex concepts in a visually attractive and easy-to-understand way.', 'A diagram showing the interconnections between Branding, SEO, and Content Marketing.'),
  ('DEPTH (Curiosity)', '"What You Didn''t Know" Video', 'Reveal little-known facts that come from the brand''s internal experience.', '"3 things that happened when we launched our first product that we never told you."'),
  ('DEPTH (Transparency)', 'Price Table or Service Comparison', 'Show value transparently in relation to the competition (objectively).', 'A simple image comparing the key features of your software vs. the market leader.'),
  ('DEPTH (Humanization)', 'The Open Letter (Genuine Message)', 'An extensive text post that explains the mission and the "why" of the brand.', 'LinkedIn post explaining the personal reason why you started your business.');
